# **🎥 MOVIE RECOMMENDATION USING APRIORI ALGORITHM**

## **📁Load the Dataset**

In [1]:
import pandas as pd
ratings=pd.read_csv("ratings.csv")
movies=pd.read_csv("movies.csv")

In [2]:
ratings.shape
ratings.info()
ratings.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100836 entries, 0 to 100835
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   userId     100836 non-null  int64
 1   movieId    100836 non-null  int64
 2   rating     100836 non-null  float64
 3   timestamp  100836 non-null  int64
dtypes: float64(1), int64(3)
memory usage: 3.1 MB

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [3]:
movies.shape
movies.info()
movies.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9742 entries, 0 to 9741
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  9742 non-null   int64
 1   title    9742 non-null   object
 2   genres   9742 non-null   object
dtypes: int64(1), object(2)
memory usage: 228.5+ KB

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

## **📊Data Preprocessing**

In [4]:
ratings.isnull().sum()

userId       0
movieId      0
rating       0
timestamp    0
dtype: int64

In [5]:
movies.isnull().sum()

movieId    0
title      0
genres     0
dtype: int64

In [6]:
ratings.duplicated().sum()

np.int64(0)

In [7]:
movies.duplicated().sum()

np.int64(0)

#### "The dataset was checked for missing and duplicate values. No missing or duplicate records were found."

In [8]:
data = pd.merge(ratings, movies, on="movieId")
data

,userId,movieId,rating,timestamp,title,genres
0,1,1,4.0,964982703,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,1,3,4.0,964981247,Grumpier Old Men (1995),Comedy|Romance
2,1,6,4.0,964982224,Heat (1995),Action|Crime|Thriller
3,1,47,5.0,964983815,Seven (a.k.a. Se7en) (1995),Mystery|Thriller
4,1,50,5.0,964982931,"Usual Suspects, The (1995)",Crime|Mystery|Thriller
...,...,...,...,...,...,...
100831,610,166534,4.0,1493848402,Split (2017),Drama|Horror|Thriller
100832,610,168248,5.0,1493850091,John Wick: Chapter Two (2017),Action|Crime|Thriller
100833,610,168250,5.0,1494273047,Get Out (2017),Horror
100834,610,168252,5.0,1493846352,Logan (2017),Action|Sci-Fi
100835,610,170875,3.0,1493846415,The Fate of the Furious (2017),Action|Crime|Drama|Thriller

In [9]:
data = data[data["rating"] >= 4]
data

,userId,movieId,rating,timestamp,title,genres
0,1,1,4.0,964982703,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,1,3,4.0,964981247,Grumpier Old Men (1995),Comedy|Romance
2,1,6,4.0,964982224,Heat (1995),Action|Crime|Thriller
3,1,47,5.0,964983815,Seven (a.k.a. Se7en) (1995),Mystery|Thriller
4,1,50,5.0,964982931,"Usual Suspects, The (1995)",Crime|Mystery|Thriller
...,...,...,...,...,...,...
100830,610,166528,4.0,1493879365,Rogue One: A Star Wars Story (2016),Action|Adventure|Fantasy|Sci-Fi
100831,610,166534,4.0,1493848402,Split (2017),Drama|Horror|Thriller
100832,610,168248,5.0,1493850091,John Wick: Chapter Two (2017),Action|Crime|Thriller
100833,610,168250,5.0,1494273047,Get Out (2017),Horror
100834,610,168252,5.0,1493846352,Logan (2017),Action|Sci-Fi

## **🔄 Transaction Encoding**

In [10]:
transactions = data.groupby("userId")["title"].apply(list)
transactions

userId
1      [Toy Story (1995), Grumpier Old Men (1995), He...
2      [Tommy Boy (1995), Good Will Hunting (1997), G...
3      [Escape from L.A. (1996), Conan the Barbarian ...
4      [Nobody Loves Me (Keiner liebt mich) (1994), F...
5      [Toy Story (1995), Get Shorty (1995), Babe (19...
                             ...
606    [Sense and Sensibility (1995), Four Rooms (199...
607    [Toy Story (1995), Dead Man Walking (1995), Wh...
608    [GoldenEye (1995), Casino (1995), Seven (a.k.a...
609    [GoldenEye (1995), Interview with the Vampire:...
610    [Toy Story (1995), Heat (1995), Casino (1995),...
Name: title, Length: 609, dtype: object

In [11]:
from mlxtend.preprocessing import TransactionEncoder
te=TransactionEncoder()
te_arr=te.fit_transform(transactions)
c=pd.DataFrame(te_arr)
c

,0,1,2,3,4,5,6,7,8,9,...,6287,6288,6289,6290,6291,6292,6293,6294,6295,6296
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
604,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
605,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
606,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
607,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
608,True,False,False,False,False,False,False,False,False,False,...,False,False,True,True,False,True,False,False,False,False

In [12]:
basket = pd.DataFrame(te_arr, columns=te.columns_)
basket.head()

,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Salem's Lot (2004),'Til There Was You (1997),"'burbs, The (1989)",(500) Days of Summer (2009),*batteries not included (1987),...And Justice for All (1979),00 Schneider - Jagd auf Nihil Baxter (1994),1-900 (06) (1994),...,Zombieland (2009),Zookeeper (2011),Zoolander (2001),Zootopia (2016),Zulu (1964),[REC] (2007),[REC]² (2009),eXistenZ (1999),xXx (2002),¡Three Amigos! (1986)
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

## **🛒 Frequent Itemset Mining using Apriori**

In [13]:
from mlxtend.frequent_patterns import apriori
frequent_itemsets=apriori(basket,min_support=0.05,use_colnames=True)
frequent_itemsets.sort_values("support",ascending=False).head()

      support                            itemsets
267  0.449918  (Shawshank Redemption, The (1994))
119  0.408867               (Forrest Gump (1994))
244  0.400657               (Pulp Fiction (1994))
273  0.369458  (Silence of the Lambs, The (1991))
206  0.364532                (Matrix, The (1999))

In [14]:
from mlxtend.frequent_patterns import association_rules
rules=association_rules(frequent_itemsets,metric="confidence",min_threshold=0.5)
rules.head(5)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(12 Angry Men (1957)),(Fargo (1996)),0.080460,0.224959,0.050903,0.632653,2.812304,1.0,0.032803,2.109834,0.700806,0.200000,0.526029,0.429465
1,(12 Angry Men (1957)),(Pulp Fiction (1994)),0.080460,0.400657,0.052545,0.653061,1.629977,1.0,0.020308,1.727519,0.420313,0.122605,0.421135,0.392104
2,(12 Angry Men (1957)),(Schindler's List (1993)),0.080460,0.287356,0.052545,0.653061,2.272653,1.0,0.029425,2.054091,0.608984,0.166667,0.513167,0.417959
3,(12 Angry Men (1957)),"(Shawshank Redemption, The (1994))",0.080460,0.449918,0.064039,0.795918,1.769030,1.0,0.027839,2.695402,0.472756,0.137324,0.628998,0.469127
4,(2001: A Space Odyssey (1968)),(Alien (1979)),0.124795,0.180624,0.072250,0.578947,3.205263,1.0,0.049709,1.946018,0.786116,0.309859,0.486130,0.489474

In [15]:
rules.sort_values("lift", ascending=False).head(10)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
210070,"(Kill Bill: Vol. 1 (2003), Star Wars: Episode ...","(Matrix, The (1999), Kill Bill: Vol. 2 (2004),...",0.067323,0.059113,0.052545,0.780488,13.203252,1.0,0.048565,4.286262,0.990977,0.711111,0.766696,0.834688
210075,"(Matrix, The (1999), Kill Bill: Vol. 2 (2004),...","(Kill Bill: Vol. 1 (2003), Star Wars: Episode ...",0.059113,0.067323,0.052545,0.888889,13.203252,1.0,0.048565,8.394089,0.982330,0.711111,0.880869,0.834688
210080,"(Kill Bill: Vol. 1 (2003), Star Wars: Episode ...","(Matrix, The (1999), Kill Bill: Vol. 2 (2004),...",0.067323,0.060755,0.052545,0.780488,12.846407,1.0,0.048455,4.278781,0.988721,0.695652,0.766289,0.822676
210063,"(Matrix, The (1999), Kill Bill: Vol. 2 (2004),...","(Kill Bill: Vol. 1 (2003), Star Wars: Episode ...",0.060755,0.067323,0.052545,0.864865,12.846407,1.0,0.048455,6.901806,0.981807,0.695652,0.855110,0.822676
210084,"(Kill Bill: Vol. 2 (2004), Star Wars: Episode ...","(Kill Bill: Vol. 1 (2003), Matrix, The (1999),...",0.067323,0.060755,0.052545,0.780488,12.846407,1.0,0.048455,4.278781,0.988721,0.695652,0.766289,0.822676
210057,"(Kill Bill: Vol. 1 (2003), Matrix, The (1999),...","(Kill Bill: Vol. 2 (2004), Star Wars: Episode ...",0.060755,0.067323,0.052545,0.864865,12.846407,1.0,0.048455,6.901806,0.981807,0.695652,0.855110,0.822676
210081,"(Kill Bill: Vol. 1 (2003), Star Wars: Episode ...","(Matrix, The (1999), Kill Bill: Vol. 2 (2004),...",0.075534,0.054187,0.052545,0.695652,12.837945,1.0,0.048452,3.107671,0.997447,0.680851,0.678216,0.832675
210062,"(Matrix, The (1999), Kill Bill: Vol. 2 (2004),...","(Kill Bill: Vol. 1 (2003), Star Wars: Episode ...",0.054187,0.075534,0.052545,0.969697,12.837945,1.0,0.048452,30.507389,0.974935,0.680851,0.967221,0.832675
210079,"(Matrix, The (1999), Kill Bill: Vol. 2 (2004),...","(Kill Bill: Vol. 1 (2003), Star Wars: Episode ...",0.062397,0.065681,0.052545,0.842105,12.821053,1.0,0.048447,5.917351,0.983363,0.695652,0.831005,0.821053
210064,"(Kill Bill: Vol. 1 (2003), Star Wars: Episode ...","(Matrix, The (1999), Kill Bill: Vol. 2 (2004),...",0.065681,0.062397,0.052545,0.800000,12.821053,1.0,0.048447,4.688013,0.986819,0.695652,0.786690,0.821053

## **🎥 Movie Recommendation Function**

In [16]:
def recommend(movie_name):

    recs = rules[rules["antecedents"].apply(lambda x: movie_name in x)]

    recs = recs.sort_values("lift", ascending=False)

    

    recommendations = []

    for movies in recs["consequents"]:
        for movie in movies:
            if movie not in recommendations:
                recommendations.append(movie)

    return recommendations[:5]

## **✅ Sample Output**

In [17]:
movie=input("enter movie name to recommend").title()
year=int(input("enter release year"))
name=f"{movie} ({year})"
recommend(name)

enter movie name to recommend toy story
enter release year 1995

['Jurassic Park (1993)',
 'Raiders of the Lost Ark (Indiana Jones and the Raiders of the Lost Ark) (1981)',
 'Star Wars: Episode V - The Empire Strikes Back (1980)',
 'Star Wars: Episode IV - A New Hope (1977)',
 'Indiana Jones and the Last Crusade (1989)']